<a href="https://colab.research.google.com/github/VictorCastro135/mineria-de-datos-178920/blob/main/Miner%C3%ADa_de_Datos.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Minería de Datos

## Primer Parcial

### Introducción

#### Conceptos

La minería de datos el proceso de extraer información útil a partir de una acumulación de datos, a menudo provenientes de un almacén o de una recopilación de data sets vinculados. Las herramientas para minería de datos incluyen potentes capacidades estadísticas, matemáticas y analíticas cuyo propósito principal es examinar grandes data sets para identificar tendencias, patrones y relaciones a fin de dar soporte a la toma de decisiones y planificación fundamentadas.

#### Ciencia de Datos

La ciencia de datos es el estudio de datos con el fin de extraer información significativa para empresas. Es un enfoque multidisciplinario que combina principios y prácticas del campo de las matemáticas, la estadística, la inteligencia artificial y la ingeniería de computación para analizar grandes cantidades de datos. Este análisis permite que los científicos de datos planteen y respondan a preguntas como “qué pasó”, “por qué pasó”, “qué pasará” y “qué se puede hacer con los resultados”.

In [ ]:
help(len)

Help on built-in function len in module builtins:

len(obj, /)
    Return the number of items in a container.



In [ ]:
len("mineria")

7

In [ ]:
len?

In [ ]:
L = [1,2,3]
L.insert?

In [ ]:
L?

In [ ]:
def square(a):
  """Return the square of a."""
  a**2

In [ ]:
square?

In [ ]:
square??

In [ ]:
len??

In [ ]:
L.append


<function list.append(object, /)>

In [ ]:
L.clear

<function list.clear()>

In [ ]:
L.count

<function list.count(value, /)>

In [ ]:
L.__add__

<method-wrapper '__add__' of list object at 0x7ff57fb5aec0>

In [ ]:
from itertools import count

In [ ]:
import itertools

In [ ]:
*Warning?

In [ ]:
str.*find*?

IPython Magic Commands

In [ ]:
# El comando mágico %timeit% sirve para evaluar el desempeño en términos de tiempo
%timeit L = [n ** 2 for n in range(1000)]

85.3 µs ± 25.2 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [ ]:
# El comando mágico %%timeit sirve también para evaluar el desempeño, solo que este abarca varias lineas de código en lugar de una
%%timeit
 L = []
for n in range(1000):
  L.append(n ** 2)

82.5 µs ± 17.1 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [ ]:
%timeit?

In [ ]:
%%timeit?

IPython and Shell Commands

In [ ]:
!ls

sample_data


In [ ]:
%cd sample_data/

/content/sample_data


In [ ]:
%ls

anscombe.json*                mnist_test.csv
california_housing_test.csv   mnist_train_small.csv
california_housing_train.csv  README.md*


In [ ]:
!cat README.md

This directory includes a few sample datasets to get you started.

*   `california_housing_data*.csv` is California housing data from the 1990 US
    Census; more information is available at:
    https://docs.google.com/document/d/e/2PACX-1vRhYtsvc5eOR2FWNCwaBiKL6suIOrxJig8LcSBbmCbyYsayia_DvPOOBlXZ4CAlQ5nlDD8kTaIDRwrN/pub

*   `mnist_*.csv` is a small sample of the
    [MNIST database](https://en.wikipedia.org/wiki/MNIST_database), which is
    described at: http://yann.lecun.com/exdb/mnist/

*   `anscombe.json` contains a copy of
    [Anscombe's quartet](https://en.wikipedia.org/wiki/Anscombe%27s_quartet); it
    was originally described in

    Anscombe, F. J. (1973). 'Graphs in Statistical Analysis'. American
    Statistician. 27 (1): 17-21. JSTOR 2682899.

    and our copy was prepared by the
    [vega_datasets library](https://github.com/altair-viz/vega_datasets/blob/4f67bdaad10f45e3549984e17e1b3088c731503d/vega_datasets/_data/anscombe.json).


In [ ]:
%env

{'SHELL': '/bin/bash',
 'COLAB_JUPYTER_TRANSPORT': 'ipc',
 'CGROUP_MEMORY_EVENTS': '/sys/fs/cgroup/memory.events /var/colab/cgroup/jupyter-children/memory.events',
 'VM_GCE_METADATA_HOST': '169.254.169.253',
 'MODEL_PROXY_HOST': 'https://mp.kaggle.net',
 'HOSTNAME': 'cddca2aa7dfd',
 'LANGUAGE': 'en_US',
 'TBE_RUNTIME_ADDR': '172.28.0.1:8011',
 'GCE_METADATA_TIMEOUT': '3',
 'COLAB_JUPYTER_IP': '172.28.0.12',
 'COLAB_LANGUAGE_SERVER_PROXY_ROOT_URL': 'http://172.28.0.1:8013/',
 'KMP_LISTEN_PORT': '6000',
 'TF_FORCE_GPU_ALLOW_GROWTH': 'true',
 'ENV': '/root/.bashrc',
 'PWD': '/',
 'TBE_EPHEM_CREDS_ADDR': '172.28.0.1:8009',
 'COLAB_LANGUAGE_SERVER_PROXY_REQUEST_TIMEOUT': '30s',
 'TBE_CREDS_ADDR': '172.28.0.1:8008',
 'COLAB_JUPYTER_TOKEN': '<hidden>',
 'LAST_FORCED_REBUILD': '20250623',
 'TCLLIBPATH': '/usr/share/tcltk/tcllib1.20',
 'COLAB_KERNEL_MANAGER_PROXY_HOST': '172.28.0.12',
 'UV_BUILD_CONSTRAINT': '',
 'COLAB_WARMUP_DEFAULTS': '1',
 'HOME': '/root',
 'LANG': 'en_US.UTF-8',
 'CLOUDSDK

Understanding Data Types in Python

In [ ]:
import numpy as np

In [ ]:
np.array([1, 4, 2, 5, 3])

array([1, 4, 2, 5, 3])

In [ ]:
np.array([3.14, 4, 2, 3])

array([3.14, 4.  , 2.  , 3.  ])

In [ ]:
np.array([1, 2, 3, 4], dtype='float32')

array([1., 2., 3., 4.], dtype=float32)

In [ ]:
np.array([1, 2, 3, 4], dtype='int')

array([1, 2, 3, 4])

In [ ]:
np.array([range(i, i + 3) for i in [2, 4, 6]])

array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

In [1]:
import numpy as np

In [2]:
x1 = np.random.randint(10, size=6)  # One-dimensional array
x2 = np.random.randint(10, size=(3, 4))  # Two-dimensional array
x3 = np.random.randint(10, size=(3, 4, 5))  # Three-dimensional array

In [3]:
print("x3 ndim: ", x3.ndim) # La propiedad ndim nos dice el número de dimensiones
print("x3 shape:", x3.shape)
print("x3 size: ", x3.size)

x3 ndim:  3
x3 shape: (3, 4, 5)
x3 size:  60


In [5]:
print(x2.dtype) # Nos dice el tipo de dato

int64


In [6]:
print("itemsize:", x3.itemsize, "bytes")
print("nbytes:", x3.nbytes, "bytes")

itemsize: 8 bytes
nbytes: 480 bytes


Array Indexing: Accessing Single Elements

In [7]:
x1

array([6, 0, 6, 5, 9, 6])

In [8]:
x1[0] # Colocamos el índice del elemento a extraer, en este caso el primer elemento tienen el indice 0

np.int64(6)

In [9]:
x1[4]

np.int64(9)

In [10]:
x1[-1] # Nos regresa el último elemento del ndarray

np.int64(6)

In [11]:
x2

array([[7, 5, 5, 2],
       [8, 3, 3, 2],
       [6, 6, 2, 3]])

In [12]:
x2[0,0]

np.int64(7)

In [13]:
x2[0,2]

np.int64(5)

In [14]:
x2[0,0] = 12 # Asignar un nuevo valor al renglón 0 columna 0
x2

array([[12,  5,  5,  2],
       [ 8,  3,  3,  2],
       [ 6,  6,  2,  3]])

#### Estadística básica

Media (Mean)

In [15]:
data = np.array([1, 2, 3, 4, 5])
media = np.mean(data)
print(media)

3.0


Promedio (Average) y Promedio Ponderado

In [16]:
data = np.array([1, 2, 3, 4, 5])
weights = np.array([1, 2, 3, 4, 5])
promedio = np.average(data)
promedio_ponderado = np.average(data, weights=weights)

In [17]:
print(promedio)
print(promedio_ponderado)

3.0
3.6666666666666665


Mediana

In [19]:
mediana = np.median(data)
print (mediana)

3.0


Varianza y Desviación Estándar

In [20]:
varianza = np.var(data)
desviacion = np.std(data)

In [21]:
print (varianza)
print (desviacion)

2.0
1.4142135623730951


Generación de Datos Aleatorios

In [22]:
muestra = np.random.normal(0, 1, 1000)
print(np.mean(muestra), np.std(muestra))

0.026968808803756825 0.977237531074634


Correlación

In [26]:
corr = np.corrcoef([1,2,3], [1,5,7])
corr

array([[1.        , 0.98198051],
       [0.98198051, 1.        ]])